plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.5'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.jakdang'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // runtimeOnly 'com.mysql:mysql-connector-j' // 이 줄을 Mysql용으로 주석 처리합니다.
    runtimeOnly 'org.postgresql:postgresql'      // 이 줄을 PostgreSQL용으로 추가합니다.
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // --- 이메일 발송 라이브러리를 추가해주세요 ---
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    // --- 아래 3줄의 JWT 라이브러리를 추가해주세요 ---
    // JWT(JSON Web Token)를 생성하고 검증하는 데 필요한 핵심 라이브러리입니다.
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
    // --- 여기까지 ---

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
}

tasks.named('test') {
    useJUnitPlatform()
}

