# Spring Boot 애플리케이션의 모든 설정을 관리하는 파일입니다.
server:
  port: 8080

spring:
  # 데이터베이스 연결 정보 (DataSource)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jakdang_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 316298

  # JPA (Java Persistence API) 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Spring Mail 설정 (올바른 위치로 이동)
  mail:
    host: smtp.gmail.com
    port: 587
    username: jakdangmoeui.certification@gmail.com
    password: quhs wpax noct cdvf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT 설정
jwt:
  secret: V293IGlzIHRoaXMgc2VjcmV0IGtleT8gSXQgaXMgYSB2ZXJ5IHNlY3JldCBrZXkuIFBsZWFzZSBkb24ndCB0ZWxsIGFueW9uZSE=
  access-token-expiration-millis: 1800000

